number1 = float(input("Enter the first number: "))
number2= float(input("Enter the second number: "))
print("Sum:", number1 + number2)
print("Difference:", number1 - number2)
print("Product:", number1 * number2)
print("Quotient:", number1 / number2 if number2 != 0 else "undefined (division by zero)")